services:

  client:
    build: ./client
    container_name: phishaid-client
    ports:
      - "3100:3100"
    environment:
      HTTPS_CA: /certs/ca.crt
      HTTPS_CERT: /certs/localhost.crt
      HTTPS_KEY: /certs/localhost.key
      WATCHPACK_POLLING: "true"
    volumes:
      - ./client:/app
      - /app/node_modules
      - ${USERPROFILE}/.office-addin-dev-certs:/certs:ro
  db:
    image: postgres:17
    container_name: phishaid-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: phishaid
      POSTGRES_USER: phishaid
      POSTGRES_PASSWORD: phishaid
    volumes:
      - phishaid_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend/phishaid
      dockerfile: Dockerfile
    container_name: phishaid-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/phishaid
      SPRING_DATASOURCE_USERNAME: phishaid
      SPRING_DATASOURCE_PASSWORD: phishaid
      VT_API_KEY: ${VT_API_KEY:-}
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  phishaid_db_data: