services:

  client:
    build: ./client
    container_name: phishaid-client
    ports:
      - "3100:3100"
    environment:
      HTTPS_CA: /certs/ca.crt
      HTTPS_CERT: /certs/localhost.crt
      HTTPS_KEY: /certs/localhost.key
      WATCHPACK_POLLING: "true"
    volumes:
      - ./client:/app
      - /app/node_modules
      - ${USERPROFILE}/.office-addin-dev-certs:/certs:ro
  db:
    image: postgres:17
    container_name: phishaid-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: phishaid
      POSTGRES_USER: phishaid
      POSTGRES_PASSWORD: phishaid
    volumes:
      - phishaid_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  phishaid_db_data: